### ISSUE TITLE
using in java code

### ISSUE THREAD

**Issue by MJ-DEV91** [mmayo888/ImageFilter#2]
How can I use this image filters in my java code?
I tried this code but I got an exception:

WekaPackageManager.loadPackages(true);

` AbstractImageFilter imageFilter = ( AbstractImageFilter ) Class.forName("weka.filters.unsupervised.instance.imagefilter.PHOGFilter" ).newInstance();`

Exception:
```
Refreshing GOE props...
Exception in thread "main" java.lang.NoClassDefFoundError: net/semanticmetadata/lire/imageanalysis/LireFeature
	java.lang.Class.forName0(Native Method)
	java.lang.Class.forName(Class.java:348)
	weka.core.WekaPackageClassLoaderManager.forName(WekaPackageClassLoaderManager.java:198)
	weka.core.WekaPackageClassLoaderManager.forName(WekaPackageClassLoaderManager.java:178)
	weka.core.ClassDiscovery.find(ClassDiscovery.java:247)
	weka.gui.GenericPropertiesCreator.generateOutputProperties(GenericPropertiesCreator.java:542)
	weka.gui.GenericPropertiesCreator.execute(GenericPropertiesCreator.java:639)
	weka.gui.GenericPropertiesCreator.regenerateGlobalOutputProperties(GenericPropertiesCreator.java:206)
	weka.core.WekaPackageManager.refreshGOEProperties(WekaPackageManager.java:1403)
	weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1328)
	weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1205)
	Main.main(Main.java:19)

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at weka.core.WekaPackageClassLoaderManager.forName(WekaPackageClassLoaderManager.java:198)
	at weka.core.WekaPackageClassLoaderManager.forName(WekaPackageClassLoaderManager.java:178)
	at weka.core.ClassDiscovery.find(ClassDiscovery.java:247)
	at weka.gui.GenericPropertiesCreator.generateOutputProperties(GenericPropertiesCreator.java:542)
	at weka.gui.GenericPropertiesCreator.execute(GenericPropertiesCreator.java:639)
	at weka.gui.GenericPropertiesCreator.regenerateGlobalOutputProperties(GenericPropertiesCreator.java:206)
	at weka.core.WekaPackageManager.refreshGOEProperties(WekaPackageManager.java:1403)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1328)
	at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1205)
	at Main.main(Main.java:19)
Caused by: java.lang.ClassNotFoundException: net.semanticmetadata.lire.imageanalysis.LireFeature
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
```

I use java 8u162

**Comment by mmayo888** [comment]
It looks like you are having a class path issue. The imageFilter's package contains several jar files and you need to ensure that they are all available to your Java program when you try to run it. If you have installed imageFilters, you should find all the jars in package directory. Other than that, the process of using the filter in java code is the same as with any other WEKA filter.

**Comment by MJ-DEV91** [comment]
Yes, you're right. I only added imageFilters.jar. Thank you.
++++++++++++++++++++++++++++++++++++
Why is it necessary that I must specify class value for applying filter? I have an arff file that contains my test set and I want to classify its files. I don't know what is the class value and when I use "?" for class value, I'll face with an Exception:

```
Exception in thread "main" weka.core.WekaException: weka.filters.unsupervised.instance.imagefilter.PHOGFilter: Cannot handle missing class values!
	at weka.core.Capabilities.test(Capabilities.java:1269)
	at weka.core.Capabilities.test(Capabilities.java:1138)
	at weka.core.Capabilities.testWithFail(Capabilities.java:1468)
	at weka.filters.Filter.testInputFormat(Filter.java:474)
	at weka.filters.Filter.setInputFormat(Filter.java:492)
	at weka.filters.SimpleFilter.setInputFormat(SimpleFilter.java:115)
	at Main.main(Main.java:33)
```

Thanks for your helpful comments.

**Comment by mmayo888** [comment]
You are right, the current version of the imageFilters seems to expect a class value for each example. We did not anticipate it being used with missing class values. The filters currently in the package are not dependent on the class, so this limitation should be removed in a future version. I will leave this issue open as a reminder.

**Comment by MJ-DEV91** [comment]
Thank you so much.

**Comment by SulimanLab** [comment]
> It looks like you are having a class path issue. The imageFilter's package contains several jar files and you need to ensure that they are all available to your Java program when you try to run it. If you have installed imageFilters, you should find all the jars in package directory. Other than that, the process of using the filter in java code is the same as with any other WEKA filter.

Thank you, this fixed my problem.
